aws_infra:
  children:
    aws_atlas

aws_dbs:
  children:
    aws_mysql
    aws_psql

aws:
  children:
    aws_mysql
    aws_psql
    aws_infra
    aws_atlas
    aws_proj
    aws_ldap
    aws_jenkins
